### ISSUE TITLE
when i use torndb as global var like `blog` demo

### ISSUE THREAD

**Issue by M2shad0w** [bdarnell/torndb#41]
help me, how to fix it, thanks
**\* Error in `python': double free or corruption (!prev): 0x000000000177da10 ***
段错误

![image](https://cloud.githubusercontent.com/assets/3387446/19218277/04c79e06-8e28-11e6-933c-aee76d598693.png)

**Comment by bdarnell** [comment]
This is either a bug in python itself or in some third-party C module you're using (probably the latter). Unfortunately there's not enough information here to tell what's going on; you're going to have to debug this in your own environment.

**Comment by M2shad0w** [comment]
this is my debug info

```
[New Thread 0x7fffe0ff9700 (LWP 19720)]
[Thread 0x7fffe8ce9700 (LWP 19129) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe1ffb700 (LWP 19203)]
0x00007fffef4f8c55 in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
Missing separate debuginfos, use: debuginfo-install python-2.7.5-34.el7.x86_64
```

``` sh
(gdb) bt
#0  0x00007fffef4f8c55 in my_real_read(st_net*, unsigned long*) ()
   from /usr/lib64/mysql/libmysqlclient.so.18
#1  0x00007fffef4f9abc in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007fffef4ec6cc in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007fffef4edbc6 in cli_read_query_result () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007fffef4eeda6 in mysql_real_query () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007fffef9cc86d in _mysql_ConnectionObject_query (self=0x105aa00, args=<optimized out>)
    at _mysql.c:2030
#6  0x00007ffff7af5aa4 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#7  0x00007ffff7af5860 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#8  0x00007ffff7af5860 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#9  0x00007ffff7af70bd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#10 0x00007ffff7af576f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#11 0x00007ffff7af70bd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#12 0x00007ffff7af576f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#13 0x00007ffff7af70bd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#14 0x00007ffff7af576f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#15 0x00007ffff7af5860 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#16 0x00007ffff7af70bd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#17 0x00007ffff7a8405d in function_call () from /lib64/libpython2.7.so.1.0
#18 0x00007ffff7a5f0b3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#19 0x00007ffff7af22f7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#20 0x00007ffff7af5860 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#21 0x00007ffff7af70bd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#22 0x00007ffff7a8405d in function_call () from /lib64/libpython2.7.so.1.0
#23 0x00007ffff7a5f0b3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#24 0x00007ffff7af22f7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#25 0x00007ffff7af5860 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#26 0x00007ffff7af5860 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
---Type <return> to continue, or q <return> to quit---
#27 0x00007ffff7af70bd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#28 0x00007ffff7a83f68 in function_call () from /lib64/libpython2.7.so.1.0
#29 0x00007ffff7a5f0b3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#30 0x00007ffff7a6e0a5 in instancemethod_call () from /lib64/libpython2.7.so.1.0
#31 0x00007ffff7a5f0b3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#32 0x00007ffff7af0f07 in PyEval_CallObjectWithKeywords () from /lib64/libpython2.7.so.1.0
#33 0x00007ffff7b25842 in t_bootstrap () from /lib64/libpython2.7.so.1.0
#34 0x00007ffff7800dc5 in start_thread (arg=0x7fffe1ffb700) at pthread_create.c:308
#35 0x00007ffff6e2528d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by M2shad0w** [comment]
Single-threaded no problem, there will be multi-threaded segment error

**Comment by smilefufu** [comment]
不一定是torndb的问题，你试试直接用MysqlDB是不是也会segment fault
