### ISSUE TITLE
Same code, it`s fine in local, but fail in server. Why?

### ISSUE THREAD

**Issue by huzhenjie** [bdarnell/torndb#44]
local is ok, but fail in server

local MySQL version: 

```
mysql  Ver 14.14 Distrib 5.7.16, for osx10.12 (x86_64) using  EditLine wrapper
```

server MySQL version:

```
mysql  Ver 14.14 Distrib 5.6.30, for Linux (x86_64) using  EditLine wrapper
```

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/Server/controller/course_controller.py", line 67, in get
    cids = get_cids(self.db, org_ids)
  File "/home/Server/data_repository.py", line 123, in get_cids
    return cs_course_dao.get_org_by_cids(db, orgIds)
  File "/home/Server/dao/cs_course_dao.py", line 29, in get_org_by_cids
    records = db.query("SELECT id from course where org_id in %(orgId)s", orgId=orgIds)
  File "/usr/lib/python2.7/site-packages/torndb.py", line 136, in query
    self._execute(cursor, query, parameters, kwparameters)
  File "/usr/lib/python2.7/site-packages/torndb.py", line 234, in _execute
    return cursor.execute(query, kwparameters or parameters)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")
```

**Comment by huzhenjie** [comment]
in commend line

exception info

```
>>> db.query("SELECT id from course where org_id in %(orgId)s", orgId=[7])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/torndb.py", line 136, in query
    self._execute(cursor, query, parameters, kwparameters)
  File "/usr/lib/python2.7/site-packages/torndb.py", line 234, in _execute
    return cursor.execute(query, kwparameters or parameters)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")
```

**Comment by smilefufu** [comment]
Check your MysqlDb version. There is a bug may cause this error at version lower than 1.2.5

**Comment by huzhenjie** [comment]
@smilefufu 

local MySQL version: `OK`

```
mysql  Ver 14.14 Distrib 5.7.16, for osx10.12 (x86_64) using  EditLine wrapper
```

server MySQL version: `Fail`

```
mysql  Ver 14.14 Distrib 5.6.30, for Linux (x86_64) using  EditLine wrapper
```

**Comment by huzhenjie** [comment]
@smilefufu 

It`s fine after upgrade `MySQL-python`.

Thank you!
